create database DAM_1
go
use DAM_1
go

-- Bảng: TAI_KHOAN
CREATE TABLE TAI_KHOAN (
    Ma_Tai_Khoan INT IDENTITY(1,1) PRIMARY KEY,
    Ten_Dang_Nhap NVARCHAR(50) NOT NULL UNIQUE,
    Mat_Khau NVARCHAR(100) NOT NULL,
    Ho_Ten NVARCHAR(100),
    Ngay_Tao DATETIME DEFAULT GETDATE(),
    Trang_Thai BIT DEFAULT 1
);

-- Bảng: VI_TIEN
CREATE TABLE VI_TIEN (
    Ma_Vi INT IDENTITY(1,1) PRIMARY KEY,
    Ten_Vi NVARCHAR(100) NOT NULL,
    So_Du DECIMAL(18, 2) DEFAULT 0.00,
    Ma_Tai_Khoan INT NOT NULL,
    CONSTRAINT FK_VI_TIEN_TAI_KHOAN FOREIGN KEY (Ma_Tai_Khoan) REFERENCES TAI_KHOAN(Ma_Tai_Khoan)
);

-- Bảng: DANH_MUC
CREATE TABLE DANH_MUC (
    Ma_Danh_Muc INT IDENTITY(1,1) PRIMARY KEY,
    Ten_Danh_Muc NVARCHAR(100) NOT NULL,
    Loai_Thu_Chi NVARCHAR(20) NOT NULL CHECK (Loai_Thu_Chi IN ('Thu', 'Chi')),
    Ma_Tai_Khoan INT NOT NULL,
    CONSTRAINT FK_DANH_MUC_TAI_KHOAN FOREIGN KEY (Ma_Tai_Khoan) REFERENCES TAI_KHOAN(Ma_Tai_Khoan)
);

-- Bảng: GIAO_DICH
CREATE TABLE GIAO_DICH (
    Ma_Giao_Dich INT IDENTITY(1,1) PRIMARY KEY,
    Ma_Vi INT NOT NULL,
    Ma_Danh_Muc INT NOT NULL,
    So_Tien DECIMAL(18, 2) NOT NULL,
    Tinh_Trang NVARCHAR(50),
    Ngay_Giao_Dich DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_GIAO_DICH_VI_TIEN FOREIGN KEY (Ma_Vi) REFERENCES VI_TIEN(Ma_Vi),
    CONSTRAINT FK_GIAO_DICH_DANH_MUC FOREIGN KEY (Ma_Danh_Muc) REFERENCES DANH_MUC(Ma_Danh_Muc)
);
