#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginRegistrationForm
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Quan_Li_Thu_Chi")]
	public partial class DataClassesDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDANH_MUC(DANH_MUC instance);
    partial void UpdateDANH_MUC(DANH_MUC instance);
    partial void DeleteDANH_MUC(DANH_MUC instance);
    partial void InsertTAI_KHOAN(TAI_KHOAN instance);
    partial void UpdateTAI_KHOAN(TAI_KHOAN instance);
    partial void DeleteTAI_KHOAN(TAI_KHOAN instance);
    partial void InsertVI_TIEN(VI_TIEN instance);
    partial void UpdateVI_TIEN(VI_TIEN instance);
    partial void DeleteVI_TIEN(VI_TIEN instance);
    partial void InsertGIAO_DICH(GIAO_DICH instance);
    partial void UpdateGIAO_DICH(GIAO_DICH instance);
    partial void DeleteGIAO_DICH(GIAO_DICH instance);
    #endregion
		
		public DataClassesDBDataContext() : 
				base(global::LoginRegistrationForm.Properties.Settings.Default.Quan_Li_Thu_ChiConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DANH_MUC> DANH_MUCs
		{
			get
			{
				return this.GetTable<DANH_MUC>();
			}
		}
		
		public System.Data.Linq.Table<TAI_KHOAN> TAI_KHOANs
		{
			get
			{
				return this.GetTable<TAI_KHOAN>();
			}
		}
		
		public System.Data.Linq.Table<VI_TIEN> VI_TIENs
		{
			get
			{
				return this.GetTable<VI_TIEN>();
			}
		}
		
		public System.Data.Linq.Table<GIAO_DICH> GIAO_DICHes
		{
			get
			{
				return this.GetTable<GIAO_DICH>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANH_MUC")]
	public partial class DANH_MUC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ma_Danh_Muc;
		
		private string _Ten_Danh_Muc;
		
		private string _Loai_Thu_Chi;
		
		private int _Ma_Tai_Khoan;
		
		private EntitySet<GIAO_DICH> _GIAO_DICHes;
		
		private EntityRef<TAI_KHOAN> _TAI_KHOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_Danh_MucChanging(int value);
    partial void OnMa_Danh_MucChanged();
    partial void OnTen_Danh_MucChanging(string value);
    partial void OnTen_Danh_MucChanged();
    partial void OnLoai_Thu_ChiChanging(string value);
    partial void OnLoai_Thu_ChiChanged();
    partial void OnMa_Tai_KhoanChanging(int value);
    partial void OnMa_Tai_KhoanChanged();
    #endregion
		
		public DANH_MUC()
		{
			this._GIAO_DICHes = new EntitySet<GIAO_DICH>(new Action<GIAO_DICH>(this.attach_GIAO_DICHes), new Action<GIAO_DICH>(this.detach_GIAO_DICHes));
			this._TAI_KHOAN = default(EntityRef<TAI_KHOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Danh_Muc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ma_Danh_Muc
		{
			get
			{
				return this._Ma_Danh_Muc;
			}
			set
			{
				if ((this._Ma_Danh_Muc != value))
				{
					this.OnMa_Danh_MucChanging(value);
					this.SendPropertyChanging();
					this._Ma_Danh_Muc = value;
					this.SendPropertyChanged("Ma_Danh_Muc");
					this.OnMa_Danh_MucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Danh_Muc", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Ten_Danh_Muc
		{
			get
			{
				return this._Ten_Danh_Muc;
			}
			set
			{
				if ((this._Ten_Danh_Muc != value))
				{
					this.OnTen_Danh_MucChanging(value);
					this.SendPropertyChanging();
					this._Ten_Danh_Muc = value;
					this.SendPropertyChanged("Ten_Danh_Muc");
					this.OnTen_Danh_MucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai_Thu_Chi", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Loai_Thu_Chi
		{
			get
			{
				return this._Loai_Thu_Chi;
			}
			set
			{
				if ((this._Loai_Thu_Chi != value))
				{
					this.OnLoai_Thu_ChiChanging(value);
					this.SendPropertyChanging();
					this._Loai_Thu_Chi = value;
					this.SendPropertyChanged("Loai_Thu_Chi");
					this.OnLoai_Thu_ChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Tai_Khoan", DbType="Int NOT NULL")]
		public int Ma_Tai_Khoan
		{
			get
			{
				return this._Ma_Tai_Khoan;
			}
			set
			{
				if ((this._Ma_Tai_Khoan != value))
				{
					if (this._TAI_KHOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_Tai_KhoanChanging(value);
					this.SendPropertyChanging();
					this._Ma_Tai_Khoan = value;
					this.SendPropertyChanged("Ma_Tai_Khoan");
					this.OnMa_Tai_KhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANH_MUC_GIAO_DICH", Storage="_GIAO_DICHes", ThisKey="Ma_Danh_Muc", OtherKey="Ma_Danh_Muc")]
		public EntitySet<GIAO_DICH> GIAO_DICHes
		{
			get
			{
				return this._GIAO_DICHes;
			}
			set
			{
				this._GIAO_DICHes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAI_KHOAN_DANH_MUC", Storage="_TAI_KHOAN", ThisKey="Ma_Tai_Khoan", OtherKey="Ma_Tai_Khoan", IsForeignKey=true)]
		public TAI_KHOAN TAI_KHOAN
		{
			get
			{
				return this._TAI_KHOAN.Entity;
			}
			set
			{
				TAI_KHOAN previousValue = this._TAI_KHOAN.Entity;
				if (((previousValue != value) 
							|| (this._TAI_KHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAI_KHOAN.Entity = null;
						previousValue.DANH_MUCs.Remove(this);
					}
					this._TAI_KHOAN.Entity = value;
					if ((value != null))
					{
						value.DANH_MUCs.Add(this);
						this._Ma_Tai_Khoan = value.Ma_Tai_Khoan;
					}
					else
					{
						this._Ma_Tai_Khoan = default(int);
					}
					this.SendPropertyChanged("TAI_KHOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GIAO_DICHes(GIAO_DICH entity)
		{
			this.SendPropertyChanging();
			entity.DANH_MUC = this;
		}
		
		private void detach_GIAO_DICHes(GIAO_DICH entity)
		{
			this.SendPropertyChanging();
			entity.DANH_MUC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAI_KHOAN")]
	public partial class TAI_KHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ma_Tai_Khoan;
		
		private string _Ten_Dang_Nhap;
		
		private string _Mat_Khau;
		
		private string _Ho_Ten;
		
		private System.Nullable<System.DateTime> _Ngay_Tao;
		
		private System.Nullable<bool> _Trang_Thai;
		
		private string _Ma_Xac_Nhan;
		
		private EntitySet<DANH_MUC> _DANH_MUCs;
		
		private EntitySet<VI_TIEN> _VI_TIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_Tai_KhoanChanging(int value);
    partial void OnMa_Tai_KhoanChanged();
    partial void OnTen_Dang_NhapChanging(string value);
    partial void OnTen_Dang_NhapChanged();
    partial void OnMat_KhauChanging(string value);
    partial void OnMat_KhauChanged();
    partial void OnHo_TenChanging(string value);
    partial void OnHo_TenChanged();
    partial void OnNgay_TaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgay_TaoChanged();
    partial void OnTrang_ThaiChanging(System.Nullable<bool> value);
    partial void OnTrang_ThaiChanged();
    partial void OnMa_Xac_NhanChanging(string value);
    partial void OnMa_Xac_NhanChanged();
    #endregion
		
		public TAI_KHOAN()
		{
			this._DANH_MUCs = new EntitySet<DANH_MUC>(new Action<DANH_MUC>(this.attach_DANH_MUCs), new Action<DANH_MUC>(this.detach_DANH_MUCs));
			this._VI_TIENs = new EntitySet<VI_TIEN>(new Action<VI_TIEN>(this.attach_VI_TIENs), new Action<VI_TIEN>(this.detach_VI_TIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Tai_Khoan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ma_Tai_Khoan
		{
			get
			{
				return this._Ma_Tai_Khoan;
			}
			set
			{
				if ((this._Ma_Tai_Khoan != value))
				{
					this.OnMa_Tai_KhoanChanging(value);
					this.SendPropertyChanging();
					this._Ma_Tai_Khoan = value;
					this.SendPropertyChanged("Ma_Tai_Khoan");
					this.OnMa_Tai_KhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Dang_Nhap", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Ten_Dang_Nhap
		{
			get
			{
				return this._Ten_Dang_Nhap;
			}
			set
			{
				if ((this._Ten_Dang_Nhap != value))
				{
					this.OnTen_Dang_NhapChanging(value);
					this.SendPropertyChanging();
					this._Ten_Dang_Nhap = value;
					this.SendPropertyChanged("Ten_Dang_Nhap");
					this.OnTen_Dang_NhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mat_Khau", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Mat_Khau
		{
			get
			{
				return this._Mat_Khau;
			}
			set
			{
				if ((this._Mat_Khau != value))
				{
					this.OnMat_KhauChanging(value);
					this.SendPropertyChanging();
					this._Mat_Khau = value;
					this.SendPropertyChanged("Mat_Khau");
					this.OnMat_KhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ho_Ten", DbType="NVarChar(100)")]
		public string Ho_Ten
		{
			get
			{
				return this._Ho_Ten;
			}
			set
			{
				if ((this._Ho_Ten != value))
				{
					this.OnHo_TenChanging(value);
					this.SendPropertyChanging();
					this._Ho_Ten = value;
					this.SendPropertyChanged("Ho_Ten");
					this.OnHo_TenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_Tao", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngay_Tao
		{
			get
			{
				return this._Ngay_Tao;
			}
			set
			{
				if ((this._Ngay_Tao != value))
				{
					this.OnNgay_TaoChanging(value);
					this.SendPropertyChanging();
					this._Ngay_Tao = value;
					this.SendPropertyChanged("Ngay_Tao");
					this.OnNgay_TaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trang_Thai", DbType="Bit")]
		public System.Nullable<bool> Trang_Thai
		{
			get
			{
				return this._Trang_Thai;
			}
			set
			{
				if ((this._Trang_Thai != value))
				{
					this.OnTrang_ThaiChanging(value);
					this.SendPropertyChanging();
					this._Trang_Thai = value;
					this.SendPropertyChanged("Trang_Thai");
					this.OnTrang_ThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Xac_Nhan", DbType="VarChar(50)")]
		public string Ma_Xac_Nhan
		{
			get
			{
				return this._Ma_Xac_Nhan;
			}
			set
			{
				if ((this._Ma_Xac_Nhan != value))
				{
					this.OnMa_Xac_NhanChanging(value);
					this.SendPropertyChanging();
					this._Ma_Xac_Nhan = value;
					this.SendPropertyChanged("Ma_Xac_Nhan");
					this.OnMa_Xac_NhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAI_KHOAN_DANH_MUC", Storage="_DANH_MUCs", ThisKey="Ma_Tai_Khoan", OtherKey="Ma_Tai_Khoan")]
		public EntitySet<DANH_MUC> DANH_MUCs
		{
			get
			{
				return this._DANH_MUCs;
			}
			set
			{
				this._DANH_MUCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAI_KHOAN_VI_TIEN", Storage="_VI_TIENs", ThisKey="Ma_Tai_Khoan", OtherKey="Ma_Tai_Khoan")]
		public EntitySet<VI_TIEN> VI_TIENs
		{
			get
			{
				return this._VI_TIENs;
			}
			set
			{
				this._VI_TIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DANH_MUCs(DANH_MUC entity)
		{
			this.SendPropertyChanging();
			entity.TAI_KHOAN = this;
		}
		
		private void detach_DANH_MUCs(DANH_MUC entity)
		{
			this.SendPropertyChanging();
			entity.TAI_KHOAN = null;
		}
		
		private void attach_VI_TIENs(VI_TIEN entity)
		{
			this.SendPropertyChanging();
			entity.TAI_KHOAN = this;
		}
		
		private void detach_VI_TIENs(VI_TIEN entity)
		{
			this.SendPropertyChanging();
			entity.TAI_KHOAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VI_TIEN")]
	public partial class VI_TIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ma_Vi;
		
		private string _Ten_Vi;
		
		private System.Nullable<decimal> _So_Du;
		
		private int _Ma_Tai_Khoan;
		
		private EntitySet<GIAO_DICH> _GIAO_DICHes;
		
		private EntityRef<TAI_KHOAN> _TAI_KHOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_ViChanging(int value);
    partial void OnMa_ViChanged();
    partial void OnTen_ViChanging(string value);
    partial void OnTen_ViChanged();
    partial void OnSo_DuChanging(System.Nullable<decimal> value);
    partial void OnSo_DuChanged();
    partial void OnMa_Tai_KhoanChanging(int value);
    partial void OnMa_Tai_KhoanChanged();
    #endregion
		
		public VI_TIEN()
		{
			this._GIAO_DICHes = new EntitySet<GIAO_DICH>(new Action<GIAO_DICH>(this.attach_GIAO_DICHes), new Action<GIAO_DICH>(this.detach_GIAO_DICHes));
			this._TAI_KHOAN = default(EntityRef<TAI_KHOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Vi", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ma_Vi
		{
			get
			{
				return this._Ma_Vi;
			}
			set
			{
				if ((this._Ma_Vi != value))
				{
					this.OnMa_ViChanging(value);
					this.SendPropertyChanging();
					this._Ma_Vi = value;
					this.SendPropertyChanged("Ma_Vi");
					this.OnMa_ViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Vi", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Ten_Vi
		{
			get
			{
				return this._Ten_Vi;
			}
			set
			{
				if ((this._Ten_Vi != value))
				{
					this.OnTen_ViChanging(value);
					this.SendPropertyChanging();
					this._Ten_Vi = value;
					this.SendPropertyChanged("Ten_Vi");
					this.OnTen_ViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_Du", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> So_Du
		{
			get
			{
				return this._So_Du;
			}
			set
			{
				if ((this._So_Du != value))
				{
					this.OnSo_DuChanging(value);
					this.SendPropertyChanging();
					this._So_Du = value;
					this.SendPropertyChanged("So_Du");
					this.OnSo_DuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Tai_Khoan", DbType="Int NOT NULL")]
		public int Ma_Tai_Khoan
		{
			get
			{
				return this._Ma_Tai_Khoan;
			}
			set
			{
				if ((this._Ma_Tai_Khoan != value))
				{
					if (this._TAI_KHOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_Tai_KhoanChanging(value);
					this.SendPropertyChanging();
					this._Ma_Tai_Khoan = value;
					this.SendPropertyChanged("Ma_Tai_Khoan");
					this.OnMa_Tai_KhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VI_TIEN_GIAO_DICH", Storage="_GIAO_DICHes", ThisKey="Ma_Vi", OtherKey="Ma_Vi")]
		public EntitySet<GIAO_DICH> GIAO_DICHes
		{
			get
			{
				return this._GIAO_DICHes;
			}
			set
			{
				this._GIAO_DICHes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAI_KHOAN_VI_TIEN", Storage="_TAI_KHOAN", ThisKey="Ma_Tai_Khoan", OtherKey="Ma_Tai_Khoan", IsForeignKey=true)]
		public TAI_KHOAN TAI_KHOAN
		{
			get
			{
				return this._TAI_KHOAN.Entity;
			}
			set
			{
				TAI_KHOAN previousValue = this._TAI_KHOAN.Entity;
				if (((previousValue != value) 
							|| (this._TAI_KHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAI_KHOAN.Entity = null;
						previousValue.VI_TIENs.Remove(this);
					}
					this._TAI_KHOAN.Entity = value;
					if ((value != null))
					{
						value.VI_TIENs.Add(this);
						this._Ma_Tai_Khoan = value.Ma_Tai_Khoan;
					}
					else
					{
						this._Ma_Tai_Khoan = default(int);
					}
					this.SendPropertyChanged("TAI_KHOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GIAO_DICHes(GIAO_DICH entity)
		{
			this.SendPropertyChanging();
			entity.VI_TIEN = this;
		}
		
		private void detach_GIAO_DICHes(GIAO_DICH entity)
		{
			this.SendPropertyChanging();
			entity.VI_TIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GIAO_DICH")]
	public partial class GIAO_DICH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ma_Giao_Dich;
		
		private int _Ma_Vi;
		
		private int _Ma_Danh_Muc;
		
		private decimal _So_Tien;
		
		private System.Nullable<bool> _Tinh_Trang;
		
		private System.Nullable<System.DateTime> _Ngay_Giao_Dich;
		
		private EntityRef<DANH_MUC> _DANH_MUC;
		
		private EntityRef<VI_TIEN> _VI_TIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_Giao_DichChanging(int value);
    partial void OnMa_Giao_DichChanged();
    partial void OnMa_ViChanging(int value);
    partial void OnMa_ViChanged();
    partial void OnMa_Danh_MucChanging(int value);
    partial void OnMa_Danh_MucChanged();
    partial void OnSo_TienChanging(decimal value);
    partial void OnSo_TienChanged();
    partial void OnTinh_TrangChanging(System.Nullable<bool> value);
    partial void OnTinh_TrangChanged();
    partial void OnNgay_Giao_DichChanging(System.Nullable<System.DateTime> value);
    partial void OnNgay_Giao_DichChanged();
    #endregion
		
		public GIAO_DICH()
		{
			this._DANH_MUC = default(EntityRef<DANH_MUC>);
			this._VI_TIEN = default(EntityRef<VI_TIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Giao_Dich", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ma_Giao_Dich
		{
			get
			{
				return this._Ma_Giao_Dich;
			}
			set
			{
				if ((this._Ma_Giao_Dich != value))
				{
					this.OnMa_Giao_DichChanging(value);
					this.SendPropertyChanging();
					this._Ma_Giao_Dich = value;
					this.SendPropertyChanged("Ma_Giao_Dich");
					this.OnMa_Giao_DichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Vi", DbType="Int NOT NULL")]
		public int Ma_Vi
		{
			get
			{
				return this._Ma_Vi;
			}
			set
			{
				if ((this._Ma_Vi != value))
				{
					if (this._VI_TIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_ViChanging(value);
					this.SendPropertyChanging();
					this._Ma_Vi = value;
					this.SendPropertyChanged("Ma_Vi");
					this.OnMa_ViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Danh_Muc", DbType="Int NOT NULL")]
		public int Ma_Danh_Muc
		{
			get
			{
				return this._Ma_Danh_Muc;
			}
			set
			{
				if ((this._Ma_Danh_Muc != value))
				{
					if (this._DANH_MUC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_Danh_MucChanging(value);
					this.SendPropertyChanging();
					this._Ma_Danh_Muc = value;
					this.SendPropertyChanged("Ma_Danh_Muc");
					this.OnMa_Danh_MucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_Tien", DbType="Decimal(15,2) NOT NULL")]
		public decimal So_Tien
		{
			get
			{
				return this._So_Tien;
			}
			set
			{
				if ((this._So_Tien != value))
				{
					this.OnSo_TienChanging(value);
					this.SendPropertyChanging();
					this._So_Tien = value;
					this.SendPropertyChanged("So_Tien");
					this.OnSo_TienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tinh_Trang", DbType="Bit")]
		public System.Nullable<bool> Tinh_Trang
		{
			get
			{
				return this._Tinh_Trang;
			}
			set
			{
				if ((this._Tinh_Trang != value))
				{
					this.OnTinh_TrangChanging(value);
					this.SendPropertyChanging();
					this._Tinh_Trang = value;
					this.SendPropertyChanged("Tinh_Trang");
					this.OnTinh_TrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_Giao_Dich", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngay_Giao_Dich
		{
			get
			{
				return this._Ngay_Giao_Dich;
			}
			set
			{
				if ((this._Ngay_Giao_Dich != value))
				{
					this.OnNgay_Giao_DichChanging(value);
					this.SendPropertyChanging();
					this._Ngay_Giao_Dich = value;
					this.SendPropertyChanged("Ngay_Giao_Dich");
					this.OnNgay_Giao_DichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANH_MUC_GIAO_DICH", Storage="_DANH_MUC", ThisKey="Ma_Danh_Muc", OtherKey="Ma_Danh_Muc", IsForeignKey=true)]
		public DANH_MUC DANH_MUC
		{
			get
			{
				return this._DANH_MUC.Entity;
			}
			set
			{
				DANH_MUC previousValue = this._DANH_MUC.Entity;
				if (((previousValue != value) 
							|| (this._DANH_MUC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DANH_MUC.Entity = null;
						previousValue.GIAO_DICHes.Remove(this);
					}
					this._DANH_MUC.Entity = value;
					if ((value != null))
					{
						value.GIAO_DICHes.Add(this);
						this._Ma_Danh_Muc = value.Ma_Danh_Muc;
					}
					else
					{
						this._Ma_Danh_Muc = default(int);
					}
					this.SendPropertyChanged("DANH_MUC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VI_TIEN_GIAO_DICH", Storage="_VI_TIEN", ThisKey="Ma_Vi", OtherKey="Ma_Vi", IsForeignKey=true)]
		public VI_TIEN VI_TIEN
		{
			get
			{
				return this._VI_TIEN.Entity;
			}
			set
			{
				VI_TIEN previousValue = this._VI_TIEN.Entity;
				if (((previousValue != value) 
							|| (this._VI_TIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VI_TIEN.Entity = null;
						previousValue.GIAO_DICHes.Remove(this);
					}
					this._VI_TIEN.Entity = value;
					if ((value != null))
					{
						value.GIAO_DICHes.Add(this);
						this._Ma_Vi = value.Ma_Vi;
					}
					else
					{
						this._Ma_Vi = default(int);
					}
					this.SendPropertyChanged("VI_TIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
